@host = http://localhost:3101

### Registro de usuario(admin)
POST {{host}}/api/users/register
Content-Type: application/json

{
    "name": "Ana Cristina Villalobos Romero",
    "email": "ana123@gmail.com",
    "password": "ana123",
    "isAdmin": true
}

### Login with cookies
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "email": "feliza@gmail.com",
    "password": "hola"
}

###  get users
GET {{host}}/api/users/

###  get users
GET {{host}}/api/Users/


### Login with cookies
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "email": "aura@mail.com",
    "password": "hola"
}


### Add product as admin
POST {{host}}/api/products
Content-Type: application/json

{
        "imageUrl": "https://res.cloudinary.com/dqoz5czqh/image/upload/v1713066960/MueblesVilla/Productos/Cocina/s4n9wrwsco1z8htattkd.webp",
        "name": "Juego de vajilla",
        "description": "Juego de vajilla de cerámica para 6 personas, incluye platos, tazas y cuencos.",
        "unit": "unidad",
        "category": "Cocina",
        "pricePerUnit": 159.99,
        "stock": 12
}

### Ver los productos con stock(admin)
GET {{host}}/api/products

### Productos por id stock(admin)
GET {{host}}/api/products/6630247554b46e1e465185a8

### Productos por precio minimo
GET {{host}}/api/products?min=400

### Productos por precio maximo
GET {{host}}/api/products?max=400

### Productos en un rango de precio
GET {{host}}/api/products?min=100&max=200

### Productos por nombre
GET {{host}}/api/products?name=mesa

### Poductos por descripcion
GET {{host}}/api/products?description=madera

### Productos por categoria
GET {{host}}/api/products?species=Cat

### Filtros combinados
GET {{host}}/api/products?max=200&category=almacenamiento

### Editar un producto como admin
PUT {{host}}/api/products/6630247554b46e1e465185a8
Content-Type: application/json

{
    "stock": 19
} 

### Borrar un producto (only admin)
DELETE {{host}}/api/products/66357e07585beb59323f437a

### Ver todos los usuarios (only admin) ............................
GET {{host}}/api/users/

### Ver el carrito de un usuario (only admin)
GET {{host}}/api/cart/user/663a8e82c4223a5212483606

### Logout
GET {{host}}/api/auth/logout


### Registro de usuario
POST {{host}}/api/users/register
Content-Type: application/json

{
    "name": "Jorge Adrian Euan Izquierdo",
    "email": "jorge1234@gmail.com",
    "password": "jorge1234"
}

### Login with cookies
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "email": "jorge1234@gmail.com",
    "password": "jorge1234"
}

### Login with cookies
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "email": "feliza@gmail.com",
    "password": "hola"
}

### Logout
GET {{host}}/api/auth/logout

### Ver los productos sin stock
GET {{host}}/api/products

### Productos por id
GET {{host}}/api/products/6630247554b46e1e465185a8

### Agregar productos al carrito
POST {{host}}/api/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlbGl6YUBnbWFpbC5jb20iLCJfaWQiOiI2NjNjMzMyODZkYjZhOGFjZDg4MzBkNjEiLCJpYXQiOjE3MTUyMjE0MDYsImV4cCI6MTcxNTIzOTQwNn0.HaUsOHjYZ8D7R2H7Exq8pq6Tmh5A2pLoLq3JTdtdLQk

{
    "productId": "663a4de37e782f19825a291f",
    "quantity": 1
}

### Ver tu carrito ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
GET {{host}}/api/cart/

### Ver tu carrito ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
DELETE  {{host}}/api/cart/


### Ver tu usuario ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
GET {{host}}/api/users/


### Editar la cantidad de un producto
PUT {{host}}/api/cart/add
Content-Type: application/json

{
    "productId": "6636e6ebab8e8b11f6980875",
    "quantity": 1
}

### Borrar producto del carrito
DELETE {{host}}/api/cart/6635808b71a99e8ccdd43af0